### ISSUE TITLE
file search does not correspond to switched project

### ISSUE THREAD

**Issue by maxheld83** [guileen/project-switcher#1]
So I do this:
1.  I open folder/project `beans` in atom
2.  `cmd+p` brings up all files in `beans`
3. `shift+cmd+p` to change to project `rice`. Tree view changes as expected. 
4. `cmd+p` brings up ...
  - *expected behavior*: files in `rice`
  - *observed behaviour*: files in `beans`

Ps.: I love the simple, single-purpose project switcher.

This is atom 0.103.0 and project switcher 0.1.0.

**Comment by ricardofbarros** [comment]
Does this still happens in the latest release?

**Comment by maxheld83** [comment]
nope, problem solved.
Thanks!
