### ISSUE TITLE
Do not read the right siblings in new Atom version

### ISSUE THREAD

**Issue by germanramos** [guileen/project-switcher#11]
When you try to change project it show the list of root directory instead of siblings of current project directory

**Comment by carloshfoliveira** [comment]
There are some 2 MR that fix this, looks like they've abandoned this project.

**Comment by ricardofbarros** [comment]
Hello, new collaborator here, it is already fixed in the last version (0.1.2), but there are still some issues. But they will be fixed soon and published.

**Comment by carloshfoliveira** [comment]
@ricardofbarros I've got a fork and since it was not being maintained, I had to publish with some corrections. If you want to take a look at it, I've corrected some tests, and add some things. Feel free to incorporate any changes I made into the core of this project :]

**Comment by ricardofbarros** [comment]
Will look into it Carlos and merge the necessary fixes, right now the latest release, fixed the deprecated calls.
