### ISSUE TITLE
cmd+; shortcut for project switcher does not work on Windows

### ISSUE THREAD

**Issue by Markavian** [guileen/project-switcher#18]
And I guess not on Linux either, examples of multi-platform key bindings here:
https://github.com/diiq/atomatigit/commit/9e8cf0364c574700374ba3dacd65ec55389cd8e3

Really like using project switcher on my Mac, really frustrated that I couldn't activate it on my windows machine. Ctrl+; seems like it would be a good alternative.

**Comment by ricardofbarros** [comment]
Good catch, I will see what to do.

**Comment by joshcoody** [comment]
As a temporary fix, you can add the following to your keymap.cson:
```
'atom-text-editor':
  'ctrl-;': 'project-switcher:toggle'
```

It's not ideal, but it does fix my issue on Windows.

**Comment by ricardofbarros** [comment]
Hello,

I totally forgot of this issue, sorry.

**Comment by ricardofbarros** [comment]
Released 0.3.0, 

could you test in windows if this issue is resolved?

**Comment by joshcoody** [comment]
Tested with version 0.3.0, and it is working now. Thanks!

**Comment by ricardofbarros** [comment]
Great :+1: Going to close it and once again sorry for the late fix.

**Comment by Markavian** [comment]
:+1: Thanks guys, much appreciated!
