### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by danielmahon** [guileen/project-switcher#8]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:54:11)
ProjectSwitcherView.toggle (/Users/daniel/Dropbox/Sync/Atom/.atom/packages/project-switcher/lib/project-switcher-view.coffee:34:11)
```

**Comment by ricardofbarros** [comment]
+1

**Comment by ricardofbarros** [comment]
Fixed in the last release.
